name: Docker
on:
  pull_request:
  push:
    branches:
    - master
    paths:
      - "*"
      - "!README.md"
      - "!tests/*"
      - "!Makefile"
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Dockerhub image
        uses: docker/login-action@v1

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin

      - name: Build & push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: ${{ github.repository }}
          tags: ${{ github.repository }}:latest