name: Docker
on:
  pull_request:
  push:
    branches:
    - master
    paths:
      - "*"
      - "!README.md"
      - "!tests/*"
      - "!Makefile"
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag adhan-scheduler

      - name: Log into registry
        run: docker login -u ${{ secrets.DOCKER_USER }} -p {{ secrets.DOCKER_PASS }}

      - name: Push image
        run: |
          IMAGE=${{ github.repository }}
          docker tag adhan-scheduler $IMAGE
          docker push $IMAGE:latest
