name: Docker
on:
  pull_request:
  push:
    branches:
    - master
    paths:
      - "*"
      - "!README.md"
      - "!tests/*"
      - "!Makefile"
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build -t adhan-scheduler .

      - name: Push image
        run: |
          docker tag adhan-scheduler luckmanali/adhan-scheduler:latest

      - name: Push image
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u luckmanali --password-stdin
          docker push luckmanali/adhan-scheduler:latest