name: Docker
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  docker:
    name: Build and publish docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag adhan-scheduler

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
      - run: |
          IMAGE=${{ github.repository }}
          docker tag adhan-scheduler $IMAGE
          docker push $IMAGE:latest
