name: Docker
on:
  pull_request:
  push:
    branches:
    - master
    paths:
      - "*"
      - "!README.md"
      - "!tests/*"
      - "!Makefile"
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build & push
        uses: docker/build-push-action@v1
        with:
          push: true
          tags: ${{ github.repository }}:latest