name: Test
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  test:
    name: Python tests on ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: upgrade pip and install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: cache packages
      uses: actions/cache@v1
      with:
          path: ~/.venv
          key: ${{ runner.os }}-build-cache-poetry-packages-${{ hashFiles('**/poetry.lock') }}

    - name: install dependencies
      run: |
        make install
    
    - name: install amixer & mplayer
      run: |
        sudo apt install alsa-utils
        sudo apt install mplayer

    - name: check lint
      run: |
        make lint

    - name: run tests
      run: |
        make test
        env:
          SUDO: True
